language: node_js
node_js:
  - 'iojs'
  - '0.10'
  - '0.12'
before_install:
  - sudo apt-get update
  - sudo apt-get install php5
  - mkdir $HOME/tmp git && clone git://github.com/CHH/phpenv.git $HOME/tmp && sh $HOME/tmp/bin/phpenv-install.sh
  - export PATH="/Users/ben/.phpenv/bin:$PATH"
  - eval "$(phpenv init -)"
  - ls $HOME/.phpenv
  - git clone git://github.com/php-build/php-build.git $HOME/.phpenv/plugins/php-build
  - phpenv install 5.6
  - phpenv global 5.6
  - php --version
  - gem update --system
  - gem install sass --version "=3.3.7"
  - npm cache clean
  - npm update -g npm
  - npm install -g bower grunt-cli jspm
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-grunt-symfony' ]; then cd .. && eval "mv $currentfolder generator-grunt-symfony" && cd generator-grunt-symfony; fi
