language: node_js
node_js:
  - 'iojs'
  - '0.10'
  - '0.12'
before_install:
  - sudo apt-get update
  - sudo apt-get install php5
  - gem update --system
  - gem install sass --version "=3.3.7"
  - npm cache clean
  - npm update -g npm
  - npm install -g bower grunt-cli jspm
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-grunt-symfony' ]; then cd .. && eval "mv $currentfolder generator-grunt-symfony" && cd generator-grunt-symfony; fi
