language: node_js
node_js:
  - 'iojs'
  - '0.10'
  - '0.12'
before_install:
  - npm install -g bower grunt-cli
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-grunt-symfony' ]; then cd .. && eval "mv $currentfolder generator-grunt-symfony" && cd generator-grunt-symfony; fi
